### ISSUE TITLE
You should make typescript a dev dependency

### ISSUE THREAD

**Issue by trajano** [therealemjy/noop-ts#1]
You should make typescript a dev dependency since it's downloading the older version of typescript as part of the install.

**Comment by dericcain** [comment]
#2 should fix this.

**Comment by therealemjy** [comment]
Hi guys,
Sorry for not checking this earlier.

@trajano You're right!

@dericcain Thank you for your contribution, I've now merged your PR with `master`.

**Comment by dericcain** [comment]
No worries! Thanks a ton!
